add pin generator
Themccarthy/si5-dsl-lab1 pull request #4
Opened 2023-11-27 12:28 UTC by claire06390

2023-11-27 20:38 UTC, Themccarthy requested changes
Le .gitignore devra être rajouté pour ignorer

2023-11-27 20:38 UTC, Themccarthy commented on External/ArduinoML-langium/src/cli/generator.ts
> +        app.bricks.forEach(brick => {
On pourrait regrouper les deux forEach en un

2023-11-27 20:46 UTC, claire06390 commented on External/ArduinoML-langium/src/cli/generator.ts
> +        app.bricks.forEach(brick => {
j'y ai pensé mais le soucis c'est qu'il faut faire le brique qui ont un port donner par l'utilisateur en premier, puis ce qu'on genere nous. Sinon ceux qu'on genere nous risque de prendre les port donnée par l'utilisateur car ils sont encore libre dans la liste

2023-11-27 20:46 UTC, claire06390 commented
@Themccarthy  tu veux que j'ajoute le fichier et le dossier généré dans le gitigonre ?

2023-11-28 07:16 UTC, Themccarthy requested changes

2023-11-28 07:16 UTC, Themccarthy commented on External/ArduinoML-langium/src/cli/generator.ts
> +        app.bricks.forEach(brick => {
J'ai une idée pour le regrouper en un seul forEach :
 - Exporter les 2 forEach dans 2 fonctions (la première L81 à L92, la deuxième L98 à L116)
 - Dans le forEach, on fait appel à la première fonction, et pour savoir si un pin a été assigné dans cette fonction, on peut comparer la taille de la liste pour voir si un pin a été pris
 - Si aucun pin n'a été pris, alors on peut passer dans la deuxième fonction

Je pense que ça devrait marcher, mais peut être qu'il y a quelque chose que j'oublie

2023-11-29 11:05 UTC, merged